ekf_filter_node:
  ros__parameters:

    use_sim_time: false
    frequency: 50.0
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true

    map_frame: map          # wird vom EKF NICHT benutzt
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # -------- ODOMETRY --------
    odom0: /utlidar/robot_odom
    odom0_config: [
      true,  true,  false,   # x, y, z
      false, false, true,    # roll, pitch, yaw
      true,  true,  false,   # vx, vy, vz
      false, false, true,    # vroll, vpitch, vyaw
      false, false, false
    ]

    # -------- IMU --------
    imu0: /utlidar/imu
    imu0_config: [
      false, false, false,   # position
      true,  true,  true,    # roll, pitch, yaw
      false, false, false,   # linear velocity
      false, false, true,    # angular velocity (yaw rate)
      false, false, false
    ]

    imu0_remove_gravitational_acceleration: true

