slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping

    # Frames
    base_frame: base_link
    odom_frame: odom
    map_frame: map

    # Sensor
    scan_topic: /scan

    # TF
    publish_tf: true
    transform_publish_period: 0.05

    # Map Topics (RViz-Fix)
    map_topic: /map
    map_update_topic: /map_updates

    # Map-Update-Frequenz
    #map_update_interval: 1.0
    #throttle_scans: 1

    # --- WICHTIG f√ºr deinen Fehler ---
    # erzwingt stabile Odom-Nutzung
    use_odom: true
    transform_timeout: 0.2
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0

